## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [2]:
import numpy as np
import pandas as pd
from scipy import stats

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [3]:
samples = np.random.normal(100, 15, 1000)
samples

array([107.77553215, 108.03335547,  91.81959928, 120.3052975 ,
       122.21640471, 117.93606629,  96.45822422,  84.34880284,
       127.43651463, 124.32422736,  90.21362715, 102.56292792,
       109.72157691, 114.49833973, 103.78674705, 131.47714786,
        77.87034363, 117.20516795, 115.97492989, 108.40500827,
        77.70693774,  85.31256178,  98.22901382, 105.86391652,
        85.73153214,  79.00942106,  98.1793417 , 108.40963947,
       132.75774613, 102.48674119,  87.03964072, 100.43293146,
       104.0891533 , 107.16432727, 100.82613035, 103.96460029,
        97.19871291,  93.52549618, 114.42533446, 116.8708648 ,
        88.56600627, 108.57298479, 101.38554709, 121.10433979,
        94.56668141, 111.09502894,  87.61737376, 122.01888612,
       132.44816599, 128.54807744,  86.14001869, 126.53321661,
        75.11668672,  97.11604557,  94.88740049, 109.29109424,
       102.01795531,  94.59625813, 103.88966722, 107.22031405,
       126.79005585,  97.36927085, 100.12145792,  87.76781563,
       102.91873768,  63.99281905, 104.03972173,  84.87043261,
       110.25160072,  89.99014407,  84.85086619,  97.69730128,
        61.67037476,  89.6789449 , 126.28298785, 102.77148123,
        97.52634775,  96.61527286,  98.64375612,  98.09371473,
        87.13398351,  86.98713815, 108.21289756,  88.453716  ,
        89.21912928, 105.97683495, 107.5688634 , 103.96078459,
       110.1445057 , 125.62946075,  84.6230667 , 109.10478257,
       108.81840784, 127.93760654, 100.86965281, 103.80945472,
        85.81245393,  69.38876563,  99.13902149, 100.49406003,
        99.10613583,  63.01268198, 120.48090452, 103.01176628,
       103.34458398,  87.26808869,  85.38465423,  82.00744171,
        80.4094422 ,  69.94468099, 108.49459354,  87.32932344,
       127.27133278,  74.30976011,  86.62017092, 105.17442269,
       116.68320542,  93.68200902, 119.70081143,  99.27937161,
        86.98188347,  93.39566594, 118.53061191,  85.75494919,
        86.3064582 ,  86.87058575,  74.14434204,  89.15307356,
       112.37051587, 104.10506954, 102.63318947, 125.48926161,
       106.02237425, 112.5522685 , 105.85467773,  77.89427694,
        95.65554312,  95.65286532,  95.41243095, 129.76516506,
       117.42703933,  98.04380973,  99.01703903,  95.35109501,
        92.02330558, 105.14721218, 104.1280158 , 114.91476186,
        82.96077081, 103.89858196,  78.43257961, 102.56589949,
        86.49429526, 127.3928992 ,  92.39299643,  97.32582988,
       103.10658656,  83.82728421,  95.2964536 ,  82.23629102,
        91.71695833, 108.33806   ,  87.2021827 , 104.72369025,
       113.16240438,  90.28274835, 112.54718167,  84.36926956,
       111.03910377, 132.97885631, 113.79958093, 100.46905973,
        60.65248647, 113.77471933, 119.80821544,  97.35180473,
       109.94587892,  91.04083296,  85.72001243,  91.39106829,
       102.43583502,  97.91998012, 107.68002915, 101.74393281,
       104.84711888, 103.93125927, 110.16618133, 115.99715391,
       101.02266077, 104.34382847,  68.79172276,  73.96710202,
        93.47228826,  92.22842477, 111.43969665, 108.29642442,
       123.41266896, 117.00910622,  87.07183388,  96.77179852,
       107.25136348,  94.98102351, 101.76405288,  81.80352598,
       112.44285715,  81.26487022, 102.0094672 ,  98.41067811,
        95.34074778, 105.73275559,  82.50968718,  92.84017577,
       113.71354872, 100.21391817, 114.30397975, 105.53406095,
        88.17957059,  83.24451111, 112.83369419,  99.22027698,
       118.0807735 , 127.63955477, 121.40845135, 101.73517179,
       104.06639946, 113.07010604,  90.67019093,  97.80334071,
        77.85688163, 100.71794134,  76.40666343, 148.20763244,
        98.70493452,  90.50526835, 112.05341138, 106.2263868 ,
       107.2717924 , 102.44568494,  86.67617281, 108.69110228,
        85.04285357,  92.60401941,  90.40865219, 122.67525148,
        93.90745288,  76.62349197, 102.9626996 ,  97.01619394,
       108.82000063, 105.80937233, 102.93453677, 104.17473939,
       100.53395883,  89.34158385,  71.47245008, 101.19282243,
        79.70761951,  78.67549757,  92.19679077,  77.38062021,
        96.14982788,  91.35402379, 113.42773479,  58.28409353,
       114.67362654,  83.28272535,  86.10450699, 138.84661192,
       118.80431281,  67.47887875,  71.00255472,  67.23268935,
       122.52551653, 103.13679674,  96.1855742 ,  81.69798651,
        87.55953237,  77.67374071,  95.16755965, 107.10226412,
        98.7933777 ,  86.03489159, 102.32383158,  97.14340062,
       115.02218424,  90.33967892, 121.62693687,  95.00232811,
       110.14524729, 108.45687432,  85.58739341, 109.14305812,
        88.09414278,  82.45854771, 109.49562078,  76.4402298 ,
       119.36556714, 103.06822035,  99.40840731, 131.93355749,
        82.82366124,  86.14265733, 106.26210677, 121.16607668,
        81.48877982,  97.32264015, 122.41588551,  96.77162235,
        99.86791572,  74.6638592 ,  75.28019874,  89.63641242,
        97.1872389 , 112.5470997 , 136.35320352, 125.05671301,
        96.69250879, 105.45453994,  97.42773977,  63.29696124,
        79.13704582, 119.32379128,  88.05209646, 111.22069415,
       112.67199824, 102.33794914, 103.35276589,  69.9201332 ,
       100.5378414 , 140.48796329, 130.43164132, 115.05682094,
        99.18945088,  94.77907003,  81.27836386,  92.42815516,
       104.78520152,  95.26882484, 105.39507808, 111.90004505,
        83.97010665,  80.46077949,  79.3676076 ,  98.73251674,
        98.33408752,  93.58998588, 121.19234546, 116.68424975,
        91.27182693, 102.57771343, 117.03287764,  88.23346405,
        88.30137289, 104.76740177, 108.30928872,  90.29121135,
       112.21960432, 104.96165297, 122.19341295,  81.78687004,
        96.20096986, 102.58645115, 103.02927903, 101.70097039,
       105.85106738,  78.51916692,  93.1834152 , 100.05573875,
        82.37416866,  71.36145058, 113.11673729, 102.34492012,
        99.37827639,  67.42037253, 102.63876492, 127.52632078,
       121.45497371, 109.32008518,  77.51189159, 108.87327141,
        99.6889272 ,  90.98851825,  78.85977007,  86.60796183,
       103.68355295, 109.57377459,  90.78675553,  82.17358338,
       109.23388158,  99.45686316, 116.6543303 , 105.15703666,
        87.76158914,  88.53992179, 105.63161118, 113.73201365,
       104.91077792,  82.88870262, 102.84239692,  98.3583076 ,
        89.75928268,  96.73149829,  77.49182835, 105.99571793,
        93.51384713, 107.43874942,  94.95552111, 104.89139726,
        88.72866557, 115.62650441,  84.80880912,  98.20681272,
       117.22655358,  92.65881143,  69.02677852,  97.26295632,
        91.28401788, 102.09981818, 105.81245849, 118.40254857,
       117.873855  ,  97.29671703, 103.25884742, 111.63724198,
        99.96481052, 110.52863742,  89.31001018,  86.12273306,
       113.62529235, 114.31213282,  66.38512239,  92.08286868,
        88.20401203, 101.26455625, 114.3970382 ,  89.5193256 ,
       104.90669256,  97.05609201,  94.70463167,  97.87812038,
        91.16403884,  93.60289914,  94.91047496, 121.04902805,
        89.37964876, 114.87819254,  92.32949974, 114.34739091,
        98.96531195, 100.82920111, 102.52057533,  99.31547399,
       115.62119123,  97.3405217 , 106.52503661, 119.39213446,
        90.58300632, 111.95113731, 106.4865465 ,  68.86475988,
        78.53561033,  92.56131924, 112.17041044,  96.96259901,
       112.73939617, 128.82672425,  74.56973924,  96.67842529,
        83.02030698, 129.53627526,  80.47924471, 104.81361699,
       103.51034809, 111.85814736, 108.56387782, 119.16018893,
        83.96323711, 110.44228066,  76.93179357, 104.82654537,
       102.95032301,  96.19928346, 118.39650583, 108.22654052,
        54.02864581,  81.35436664,  86.59076538, 116.91605212,
       118.04853875, 132.43616144, 112.57800084, 114.55816901,
       104.63261831, 112.80020898,  80.0831762 , 104.39286332,
       124.29732919, 103.62291418, 122.94393037,  87.33537193,
       100.09465471,  96.92756922, 109.51701694,  88.76486281,
        97.50853018, 110.26992805, 116.91621958,  86.59940313,
        91.80150989,  97.80903241,  98.77132703,  99.51055332,
       105.35312953,  88.87354629, 123.17693043,  92.61826859,
        75.4245681 ,  94.42608728, 102.36192787, 108.40749595,
       113.72094078,  84.0816481 , 107.78462153, 108.49246105,
       108.34926222,  98.64730995,  84.23039433, 109.14661692,
        94.8667401 ,  95.40765953,  67.82669431, 138.23064061,
       126.16285859,  99.7851209 , 107.11890409, 101.9180097 ,
        98.59394472, 101.42311031, 102.40254647, 102.00302241,
        96.01961355, 105.29469524, 109.73084308, 104.04286866,
       121.5106583 ,  89.25234918, 109.00566051,  90.59856881,
       105.37598136,  85.13700933, 105.39181543,  98.66549684,
       124.15882451,  94.87478336,  82.10235597, 100.26848203,
       109.84662404,  74.45838613, 113.69451709, 102.18935202,
       114.96596554, 100.25132951, 118.0580142 , 108.6039503 ,
       105.75932344,  61.66253979, 137.66836674,  94.50201252,
       100.70329632,  73.43495862, 119.10682722,  90.17287912,
        87.13115203,  91.24197787,  71.63390939,  75.86499594,
        92.58199794, 104.23010041,  84.76111958,  93.51989533,
       121.00206876, 102.2283233 , 129.59741013, 104.70266815,
        88.51048475,  95.84089928, 103.12190137,  64.87578365,
        97.65355033,  61.41128307,  91.98841965,  88.86326877,
       107.93241684, 117.88219835, 111.10756876,  96.36562554,
        99.30481718, 114.15211478, 109.52684384,  95.62932043,
        93.04586998, 101.56718142, 109.97755483, 105.44736365,
        92.24421342,  91.53005984,  69.31250787,  86.76287898,
       128.93223911, 113.68083983,  86.92211472, 129.25241775,
       110.22678132, 125.30495644, 123.92126623,  95.24942957,
        88.16062009, 112.60980588, 107.58468824, 108.44048641,
       105.48968899, 100.30773784,  66.79472535, 114.54325806,
       121.43390662, 107.26967686, 142.55286871,  89.26265412,
        98.68063573,  92.80759945, 110.57934638,  93.47071634,
        77.95063064,  97.98872068, 119.35147837, 123.45015923,
       100.47070142, 113.45507983,  76.03648356,  79.66804072,
        87.99119708, 103.08054989,  98.08267121,  92.82033706,
        96.61240126,  98.85503561,  99.14139838, 105.96013085,
       111.03720684, 110.80222866, 104.04140791,  81.37013223,
       104.88249179,  94.4582815 , 106.05771062, 104.14354683,
       100.77685946,  99.04541011, 115.30000677, 128.7405744 ,
       112.26234079,  97.57258741,  89.10352418, 123.33671544,
        73.75061332,  95.94494444, 113.27185157, 111.35405331,
       111.50327253, 115.91193756, 105.29137235, 102.85495677,
       105.91912742,  88.20065696, 107.93580988, 107.07892455,
        92.96031212, 100.54475593,  86.70679197,  69.31824668,
        96.52329551,  79.93958565, 100.46708082, 103.50604003,
       121.55924102, 133.68365757,  81.12585213,  94.23949634,
       115.44742933, 119.7835506 ,  91.66017628, 124.65651576,
       114.26673044, 106.04028503, 114.22967583, 100.51181967,
        61.26312945, 130.21737013, 117.28145876,  90.87118817,
       113.77206322,  70.66001834,  69.55873291,  95.83224177,
       101.00280546,  79.52448773,  65.59325033,  95.13116386,
        86.7271309 ,  85.95230085, 106.57057215, 102.46862087,
       105.81410436, 108.36306381,  82.74864173,  82.60668616,
        79.25554346, 104.06437917, 101.46613002, 145.05071832,
       121.69558167,  85.51793832, 121.97432675,  89.07957447,
        76.42842027, 102.21921164, 108.82259923,  79.36779578,
       108.03437649,  89.66140271, 117.33592363,  80.30198652,
       101.53543429, 113.70152659,  95.5637176 , 126.97797029,
       120.28452159,  90.01678191,  98.29482214, 101.52507822,
        76.73982204,  89.17051721, 104.04875465,  88.41527098,
       106.30253824, 119.27724283, 104.10696062,  90.63843966,
        79.17251682, 108.1186934 ,  97.10734807,  97.09001504,
       102.0754292 ,  85.38390266,  89.78747889,  87.27554762,
        96.338479  ,  94.2854661 ,  87.31506951,  78.73072031,
       107.30024922,  75.64719828, 105.29990742,  90.94160114,
        99.82358336,  80.19614204, 117.44784092, 108.904345  ,
        84.8700018 ,  75.33365897,  66.11299309, 118.97257826,
       107.0326561 , 108.12683333, 104.84064981,  95.77553574,
        87.34180709,  83.31683231,  94.35043982,  87.87287196,
        93.01929158, 117.418854  , 112.63900274, 115.3582323 ,
       113.90505991,  94.69356155, 121.07908601, 123.33118036,
       119.25248726, 106.67162747,  95.29396428, 113.92068246,
        92.97094159, 119.48582674, 127.74143949, 123.78933798,
        97.70235716,  97.63937035, 105.27111245,  92.76581592,
        96.01421121,  88.79610181,  93.54445121,  80.78289865,
       112.43687891,  84.30917905,  71.5316005 ,  90.20427266,
       115.5531674 ,  83.10456664, 113.16453976, 106.04478173,
        91.02172827, 115.1158955 ,  99.25716634, 111.3330425 ,
       128.46549916,  72.64407161, 121.06655341,  95.90929243,
       114.70172672,  90.08592552,  86.81698934, 108.2857214 ,
       123.0037864 ,  87.56094059,  95.25079136,  90.16539706,
       121.24290478, 104.91588191,  79.09860455, 107.45335856,
        88.07616986, 107.43302522, 114.11050614, 118.77429422,
        82.17901785, 119.11718252,  85.61088057, 104.88507011,
       114.50554271,  66.37651679, 111.45591558,  70.99358695,
       121.20562028,  95.89762912,  95.72117431,  87.72764576,
       106.78493679, 102.34456315,  74.97930557, 116.45533529,
       119.95619991,  82.75378507, 106.3369557 ,  91.40444055,
       112.28359791,  98.44042789,  78.2708298 ,  75.08224224,
        96.13418236, 117.8163324 ,  90.94717965, 118.22945344,
        61.79766121, 107.16380178, 107.56015504, 117.11747589,
       109.10023795,  87.43019666,  78.95861731,  85.36610677,
       113.80941523, 115.27647534, 103.41012191,  94.40472078,
        95.11528459, 115.37637708, 121.37556189,  78.0385623 ,
        78.13159061,  88.26866597,  99.89282341,  87.51067365,
        85.36087743, 104.66922114, 105.32033307,  97.6710416 ,
        99.08530087,  97.78367814,  71.00579689,  98.22110795,
        99.0840735 ,  81.26521226, 100.61453787, 101.91333181,
        95.42982852,  92.52196513, 127.69638354, 117.64148771,
       120.1098148 , 110.33018834, 119.7915787 , 120.23274416,
       117.01582673, 122.1792592 , 103.51022831,  87.21362117,
        80.98788844,  98.1886476 , 110.25531298,  97.67429053,
        95.14798131,  97.44655255,  98.07017602, 106.56718978,
        69.19619999,  81.45827265,  81.67661394, 106.051829  ,
       121.18996172,  86.11924288, 110.93485104,  86.73609594,
       116.41276862,  88.65489676, 106.97305475,  71.7797874 ,
       135.32064299,  90.63119294,  70.1780658 , 102.18141488,
        76.79683859,  90.32548855, 129.75207954, 125.82331704,
       106.50422797, 107.93208936,  93.52794243, 117.44491091,
       102.63227976, 109.79092875,  97.55755284, 100.67244631,
       105.63094208,  75.56648644, 108.16560617, 118.1273569 ,
        80.75572004,  89.36877483,  77.24743718,  91.44926224,
       108.05570302, 101.15862163, 110.98438616, 116.2015084 ,
        89.69325015,  93.04993152, 108.38993406, 102.09329686,
       105.6968668 ,  81.70366963, 128.45990336,  91.50268313,
        91.78828069, 107.03311993,  99.02048307,  59.99311769,
       116.29543934,  84.92640029, 118.3877265 , 106.91630641,
        83.69242068, 101.30827443, 107.02626748,  98.49949552,
        99.35426371,  81.06538466,  95.89208213, 100.50659077,
       109.28212628,  89.60273629, 106.2869129 , 134.94245135,
        84.10031546, 109.89533281,  98.41253513, 104.88157077,
       114.8071035 , 113.23839905, 111.07227572,  90.38447985,
        95.58271603, 106.41230107,  94.65941139,  97.5399635 ,
        91.04331853, 107.42857977, 100.65971255,  89.44087006])

Compute the **mean**, **median**, and **mode**

In [4]:
mean = np.mean(samples)
median = np.median(samples)
mode = stats.mode(samples)

print("mean :", mean)
print("median :", median)
print("mode :", mode)

mean : 99.98095029811792
median : 100.46988057479228
mode : ModeResult(mode=array([54.02864581]), count=array([1]))

Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [ ]:
from numpy.random.mtrand import sample
min = np.min(samples)
max = np.max(samples)
q1 = np.percentile(samples, 25)
q3 = np.percentile(samples, 75)
iqr = stats.iqr(samples)

print("min :", min)
print("max :", max)
print("q1 :", q1)
print("q3 :", q3)
print("iqr :", iqr)

min : 48.53730534288019
max : 149.62625068446053
q1 : 91.14731391634174
q3 : 111.63797972369434
iqr : 20.4906658073526

Compute the **variance** and **standard deviation**

In [ ]:
variance = np.var(samples)
std_dev = np.std(samples)

print("variance :", variance)
print("standart deviation :", std_dev)

variance : 228.7831900912204
standart deviation : 15.125580653026859

Compute the **skewness** and **kurtosis**

In [ ]:
skewness = stats.skew(samples)
kurtosis = stats.kurtosis(samples)

print("skewness :", skewness)
print("kurtosis :", kurtosis)

skewness : -0.012121099683658536
kurtosis : 0.04399016109062437

## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [5]:
x = np.arange(10,20)
print(x)

[10 11 12 13 14 15 16 17 18 19]

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [8]:
y = np.array([3, 5, 1, 6, 9, 2, 4, 8, 7, 10])
print(y)

[ 3  5  1  6  9  2  4  8  7 10]

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [9]:
r = np.corrcoef(x,y)
print(r)

[[1.  0.6]
 [0.6 1. ]]

## Pandas Correlation Calculation

Run the code below

In [10]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [14]:
r = stats.pearsonr(x,y)
print(r)  # gives us pearson's correlation coefficient and p-value

(0.758640289091187, 0.010964341301680813)

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [15]:
rho = stats.spearmanr(x,y)
print(rho)  # gives us spearsman's correlation coefficient and p-value

SpearmanrResult(correlation=0.9757575757575757, pvalue=1.4675461874042197e-06)

## Seaborn Dataset Tips

Import Seaborn Library

In [16]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [17]:
tips = sns.load_dataset("tips")

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [18]:
tips.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [19]:
tips.corr()

            total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000